POST http://localhost:23990/api/socks/income
Content-Type: application/json

{
  "color": "black",
  "cottonPart": 10,
  "quantity": 10
}

###

POST http://localhost:23990/api/socks/outcome
Content-Type: application/json

{
  "color": "black",
  "cottonPart": 10,
  "quantity": 20
}
