-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: src/main/resources/db/changelog/db.changelog-master.xml
-- Ran at: 20.10.2021, 21:25
-- Against: postgres@jdbc:postgresql://localhost/socks
-- Liquibase version: 4.3.5
-- *********************************************************************

SET SEARCH_PATH TO public;

SET SEARCH_PATH TO public;

-- Create Database Lock Table
CREATE TABLE databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT DATABASECHANGELOGLOCK_PKEY PRIMARY KEY (ID));

-- Initialize Database Lock Table
DELETE FROM databasechangeloglock;

INSERT INTO databasechangeloglock (ID, LOCKED) VALUES (1, FALSE);

-- Lock Database
UPDATE databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'admin-pc (192.168.1.53)', LOCKGRANTED = '2021-10-20 21:25:47.755' WHERE ID = 1 AND LOCKED = FALSE;

SET SEARCH_PATH TO public;

-- Create Database Change Log Table
CREATE TABLE databasechangelog (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP WITHOUT TIME ZONE NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10));

SET SEARCH_PATH TO public;

SET SEARCH_PATH TO public;

-- Changeset src/main/resources/db/changelog/changes/2021-09-12--01-sock-and-color-schema.xml::2021-09-12--01-sock-and-color-schema::svetashov
SET SEARCH_PATH TO public;

CREATE TABLE color (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, CONSTRAINT COLOR_PKEY PRIMARY KEY (id), UNIQUE (name));

CREATE TABLE sock (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, color_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cotton_part INTEGER NOT NULL, quantity INTEGER NOT NULL, CONSTRAINT SOCK_PKEY PRIMARY KEY (id));

ALTER TABLE sock ADD CONSTRAINT sock_color_color_id_fk FOREIGN KEY (color_id) REFERENCES color (id);

INSERT INTO databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('2021-09-12--01-sock-and-color-schema', 'svetashov', 'src/main/resources/db/changelog/changes/2021-09-12--01-sock-and-color-schema.xml', NOW(), 1, '8:8a34bcb71ec5a03b7ddb1dedc996d154', 'createTable tableName=color; createTable tableName=sock; addForeignKeyConstraint baseTableName=sock, constraintName=sock_color_color_id_fk, referencedTableName=color', '', 'EXECUTED', NULL, NULL, '4.3.5', '4754350129');

-- Changeset src/main/resources/db/changelog/changes/2021-09-12--02-unique-constraint.xml::2021-09-12--02-unique-constraint::svetashov
SET SEARCH_PATH TO public;

ALTER TABLE sock ADD CONSTRAINT sock_color_id_cotton_part_unique UNIQUE (color_id, cotton_part);

INSERT INTO databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('2021-09-12--02-unique-constraint', 'svetashov', 'src/main/resources/db/changelog/changes/2021-09-12--02-unique-constraint.xml', NOW(), 2, '8:633df65ed40aa55655661a7b1bcf0e69', 'addUniqueConstraint constraintName=sock_color_id_cotton_part_unique, tableName=sock', '', 'EXECUTED', NULL, NULL, '4.3.5', '4754350129');

-- Changeset src/main/resources/db/changelog/changes/2021-09-12--03-init-colors.xml::2021-09-12--03-init-colors::svetashov
SET SEARCH_PATH TO public;

INSERT INTO color (name) VALUES ('black');

INSERT INTO color (name) VALUES ('red');

INSERT INTO color (name) VALUES ('yellow');

INSERT INTO databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('2021-09-12--03-init-colors', 'svetashov', 'src/main/resources/db/changelog/changes/2021-09-12--03-init-colors.xml', NOW(), 3, '8:942b8150596a4b9e319d7f0fe3ec50a4', 'insert tableName=color; insert tableName=color; insert tableName=color', '', 'EXECUTED', NULL, NULL, '4.3.5', '4754350129');

-- Release Database Lock
SET SEARCH_PATH TO public;

UPDATE databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

SET SEARCH_PATH TO public;

