version: "3"
services:
  app:
    build: .
    container_name: app
    ports:
      - 8082:8080
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
     # - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:latest
    container_name: db
    ports:
      - 15000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=public
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped