drop table if exists socks cascade;
create table socks
(
    id         int8 generated by default as identity,
    color      varchar(255),
    cotton_part int2,
    quantity   int8,
    primary key (id)
);
alter table if exists socks
    add constraint socks_unique_fk unique (color, cotton_part);