create table socks
(
    id          int8 generated by default as identity,
    color       varchar(255) not null,
    cotton_part int2 check (cotton_part <= 100 AND cotton_part >= 0),
    quantity    int4 not null check (quantity >= 1),
    primary key (id)
);