-- create sequence socks_id_seq;
--
-- alter sequence socks_id_seq owner to xtwcnzmyfnqavm;
--
-- alter sequence socks_id_seq owned by socks.id;
create table socks (
    id int4 generated by default as identity not null ,
     color varchar(255) not null,
      cotton_part int8 not null,
       quantity int8 not null ,
        primary key (id))