CREATE TABLE IF NOT EXISTS public.sock
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    color character varying(100) NOT NULL COLLATE pg_catalog."default",
    cottonpart integer,
    quantity integer,
    CONSTRAINT sock_pkey PRIMARY KEY (id)
)