create table socks
(
    id          int8 generated by default as identity,
    color       varchar(255),
    cotton_part int8,
    quantity    int8,
    primary key (id)
);
INSERT INTO socks (color, cotton_part, quantity)
VALUES ('blue', 99, 50);
INSERT INTO socks (color, cotton_part, quantity)
VALUES ('red', 59, 50);
INSERT INTO socks (color, cotton_part, quantity)
VALUES ('green', 99, 50);
INSERT INTO socks (color, cotton_part, quantity)
VALUES ('white', 10, 50);