create table sock(
    id int8 generated by default as identity,
    color varchar(255),
    cotton_part int8,
    quantity int8,
    primary key(id)
);

insert into sock(color, cotton_part,quantity)
values('white',43,70);
insert into sock(color, cotton_part,quantity)
values('red',24,50);